/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitormanagement;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author jimmelbermudez7
 */
public class vmsubmodules extends javax.swing.JPanel {
GridBagLayout layout=new GridBagLayout();
     vregistration a1;
     visitation a2;
     notification a3;
     vreports a4;
     VM a5;
    /**
     * Creates new form vmsudmodules
     */
    public vmsubmodules() {
        initComponents();
        a1=new vregistration();
        a2=new visitation();
        a3=new notification();
        a4=new vreports();
        a5=new VM();
        home3.setLayout(layout);
        GridBagConstraints a=new GridBagConstraints();
        a.gridx=0;
        a.gridy=0;
        home3.add(a1,a);
        home3.add(a2,a);
        home3.add(a3,a);
        home3.add(a4,a);
        home3.add(a5,a);
         a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(false);
        a5.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        visitation = new javax.swing.JButton();
        registration = new javax.swing.JButton();
        Events = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        home3 = new javax.swing.JPanel();
        reports1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 0));
        setPreferredSize(new java.awt.Dimension(1220, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 192, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visitation.setBackground(new java.awt.Color(0, 204, 255));
        visitation.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        visitation.setText("Visitation");
        visitation.setToolTipText("");
        visitation.setBorder(null);
        visitation.setContentAreaFilled(false);
        visitation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        visitation.setOpaque(true);
        visitation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visitationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                visitationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                visitationMouseExited(evt);
            }
        });
        visitation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitationActionPerformed(evt);
            }
        });
        jPanel1.add(visitation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, 30));

        registration.setBackground(new java.awt.Color(0, 204, 255));
        registration.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        registration.setText("Registration");
        registration.setToolTipText("");
        registration.setBorder(null);
        registration.setContentAreaFilled(false);
        registration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registration.setOpaque(true);
        registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrationMouseExited(evt);
            }
        });
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        jPanel1.add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 200, 30));

        Events.setBackground(new java.awt.Color(0, 204, 255));
        Events.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Events.setText("Events");
        Events.setToolTipText("");
        Events.setBorder(null);
        Events.setContentAreaFilled(false);
        Events.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Events.setOpaque(true);
        Events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EventsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EventsMouseExited(evt);
            }
        });
        Events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventsActionPerformed(evt);
            }
        });
        jPanel1.add(Events, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 200, 30));

        reports.setBackground(new java.awt.Color(0, 204, 255));
        reports.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reports.setText("Reports");
        reports.setToolTipText("");
        reports.setBorder(null);
        reports.setContentAreaFilled(false);
        reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reports.setOpaque(true);
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        jPanel1.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 200, 30));

        home3.setBackground(new java.awt.Color(108, 192, 240));
        home3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(home3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1220, 580));

        reports1.setBackground(new java.awt.Color(0, 204, 255));
        reports1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reports1.setText("D");
        reports1.setToolTipText("");
        reports1.setBorder(null);
        reports1.setContentAreaFilled(false);
        reports1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reports1.setOpaque(true);
        reports1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reports1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reports1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reports1MouseExited(evt);
            }
        });
        reports1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reports1ActionPerformed(evt);
            }
        });
        jPanel1.add(reports1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void visitationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visitationMouseClicked

    private void visitationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitationMouseEntered


        // TODO add your handling code here:
    }//GEN-LAST:event_visitationMouseEntered

    private void visitationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitationMouseExited


        // TODO add your handling code here:
    }//GEN-LAST:event_visitationMouseExited

    private void visitationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitationActionPerformed
reports1.setForeground(new java.awt.Color(0,0,0));
        registration.setForeground(new java.awt.Color(0,0,0));
        visitation.setForeground(new java.awt.Color(255,255,255));
        Events.setForeground(new java.awt.Color(0,0,0));
        reports.setForeground(new java.awt.Color(0,0,0));
        a5.setVisible(false);a1.setVisible(false);
         a2.setVisible(true);
         a3.setVisible(false);
         a4.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_visitationActionPerformed

    private void registrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationMouseClicked

    private void registrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationMouseEntered

    private void registrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationMouseExited

    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
reports1.setForeground(new java.awt.Color(0,0,0));
        registration.setForeground(new java.awt.Color(255,255,255));
        visitation.setForeground(new java.awt.Color(0,0,0));
        Events.setForeground(new java.awt.Color(0,0,0));
        reports.setForeground(new java.awt.Color(0,0,0));
        a1.setVisible(true);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(false); 
         a5.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_registrationActionPerformed

    private void EventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EventsMouseClicked

    private void EventsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EventsMouseEntered

    private void EventsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventsMouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_EventsMouseExited

    private void EventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventsActionPerformed
reports1.setForeground(new java.awt.Color(0,0,0));
        registration.setForeground(new java.awt.Color(0,0,0));
        visitation.setForeground(new java.awt.Color(0,0,0));
        Events.setForeground(new java.awt.Color(255,255,255));
        reports.setForeground(new java.awt.Color(0,0,0));
        a5.setVisible(false);
        a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(true);
         a4.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_EventsActionPerformed

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseClicked

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseExited

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed

        reports1.setForeground(new java.awt.Color(0,0,0));
        registration.setForeground(new java.awt.Color(0,0,0));
        visitation.setForeground(new java.awt.Color(0,0,0));
        Events.setForeground(new java.awt.Color(0,0,0));
        reports.setForeground(new java.awt.Color(255,255,255));
        a5.setVisible(false);
        a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_reportsActionPerformed

    private void reports1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseClicked

    private void reports1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseEntered

    private void reports1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseExited
              // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseExited

    private void reports1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reports1ActionPerformed
        reports1.setForeground(new java.awt.Color(255,255,255));
        registration.setForeground(new java.awt.Color(0,0,0));
        visitation.setForeground(new java.awt.Color(0,0,0));
        Events.setForeground(new java.awt.Color(0,0,0));
        reports.setForeground(new java.awt.Color(0,0,0));
        
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_reports1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Events;
    private javax.swing.JPanel home3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registration;
    private javax.swing.JButton reports;
    private javax.swing.JButton reports1;
    private javax.swing.JButton visitation;
    // End of variables declaration//GEN-END:variables
}
