/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facilityreservation;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author jimmelbermudez7
 */
public class frsubmodules extends javax.swing.JPanel {
GridBagLayout layout=new GridBagLayout();
     monitoring a1;
     registration a2;
     reservation a3;
     reports a4;
     FR a5;
    /**
     * Creates new form frsubmodules
     */
    public frsubmodules() {
        initComponents();
        a1=new monitoring();
        a2=new registration();
        a3=new reservation();
        a4=new reports();
        a5=new FR();
        home2.setLayout(layout);
        GridBagConstraints a=new GridBagConstraints();
        a.gridx=0;
        a.gridy=0;
        home2.add(a1,a);
        home2.add(a2,a);
        home2.add(a3,a);
        home2.add(a4,a);
        home2.add(a5,a);
         a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(false);
         a5.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        request = new javax.swing.JButton();
        monitoring = new javax.swing.JButton();
        reservation = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        d = new javax.swing.JButton();
        home2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 51, 153));
        setPreferredSize(new java.awt.Dimension(1220, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 192, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        request.setBackground(new java.awt.Color(0, 204, 255));
        request.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        request.setText("Request for Facility");
        request.setToolTipText("");
        request.setBorder(null);
        request.setContentAreaFilled(false);
        request.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        request.setOpaque(true);
        request.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                requestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                requestMouseExited(evt);
            }
        });
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });
        jPanel1.add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, 30));

        monitoring.setBackground(new java.awt.Color(0, 204, 255));
        monitoring.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        monitoring.setText("Monitoring");
        monitoring.setToolTipText("");
        monitoring.setBorder(null);
        monitoring.setContentAreaFilled(false);
        monitoring.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        monitoring.setOpaque(true);
        monitoring.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monitoringMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monitoringMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monitoringMouseExited(evt);
            }
        });
        monitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitoringActionPerformed(evt);
            }
        });
        jPanel1.add(monitoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 200, 30));

        reservation.setBackground(new java.awt.Color(0, 204, 255));
        reservation.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reservation.setText("Reservation");
        reservation.setToolTipText("");
        reservation.setBorder(null);
        reservation.setContentAreaFilled(false);
        reservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservation.setOpaque(true);
        reservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservationMouseExited(evt);
            }
        });
        reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationActionPerformed(evt);
            }
        });
        jPanel1.add(reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 200, 30));

        reports.setBackground(new java.awt.Color(0, 204, 255));
        reports.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reports.setText("Reports");
        reports.setToolTipText("");
        reports.setBorder(null);
        reports.setContentAreaFilled(false);
        reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reports.setOpaque(true);
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        jPanel1.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 200, 30));

        d.setBackground(new java.awt.Color(0, 204, 255));
        d.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        d.setText("D");
        d.setContentAreaFilled(false);
        d.setOpaque(true);
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        home2.setBackground(new java.awt.Color(108, 192, 240));
        home2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1220, 580));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void requestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_requestMouseClicked

    private void requestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestMouseEntered

    
        // TODO add your handling code here:
    }//GEN-LAST:event_requestMouseEntered

    private void requestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestMouseExited
   

        // TODO add your handling code here:
    }//GEN-LAST:event_requestMouseExited

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
d.setForeground(new java.awt.Color(000,000,000));
monitoring.setForeground(new java.awt.Color(000,000,000));
request.setForeground(new java.awt.Color(255,255,255));
reservation.setForeground(new java.awt.Color(000,000,000)); 
reports.setForeground(new java.awt.Color(000,000,000)); 
        a1.setVisible(false);
         a2.setVisible(true);
         a3.setVisible(false);
         a4.setVisible(false);
        a5.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_requestActionPerformed

    private void monitoringMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitoringMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_monitoringMouseClicked

    private void monitoringMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitoringMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_monitoringMouseEntered

    private void monitoringMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitoringMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_monitoringMouseExited

    private void monitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitoringActionPerformed
d.setForeground(new java.awt.Color(000,000,000));
monitoring.setForeground(new java.awt.Color(255,255,255));
request.setForeground(new java.awt.Color(000,000,000));
reservation.setForeground(new java.awt.Color(000,000,000)); 
reports.setForeground(new java.awt.Color(000,000,000)); 
        a1.setVisible(true);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(false);
         a5.setVisible(false);
                // TODO add your handling code here:
    }//GEN-LAST:event_monitoringActionPerformed

    private void reservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationMouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_reservationMouseClicked

    private void reservationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reservationMouseEntered

    private void reservationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationMouseExited

    }//GEN-LAST:event_reservationMouseExited

    private void reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationActionPerformed
d.setForeground(new java.awt.Color(000,000,000));
monitoring.setForeground(new java.awt.Color(000,000,000));
request.setForeground(new java.awt.Color(000,000,000));
reservation.setForeground(new java.awt.Color(255,255,255)); 
reports.setForeground(new java.awt.Color(000,000,000));       
        a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(true);
         a4.setVisible(false);
           a5.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_reservationActionPerformed

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseClicked

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
      // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseExited

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
d.setForeground(new java.awt.Color(000,000,000));
monitoring.setForeground(new java.awt.Color(000,000,000));
request.setForeground(new java.awt.Color(000,000,000));
reservation.setForeground(new java.awt.Color(000,000,000)); 
reports.setForeground(new java.awt.Color(255,255,255)); 
        a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(true);
         a5.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_reportsActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
d.setForeground(new java.awt.Color(255,255,255));
monitoring.setForeground(new java.awt.Color(000,000,000));
request.setForeground(new java.awt.Color(000,000,000));
reservation.setForeground(new java.awt.Color(000,000,000)); 
reports.setForeground(new java.awt.Color(000,000,000)); 
        a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(false);
         a5.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton d;
    private javax.swing.JPanel home2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton monitoring;
    private javax.swing.JButton reports;
    private javax.swing.JButton request;
    private javax.swing.JButton reservation;
    // End of variables declaration//GEN-END:variables
}
