/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facilityreservation;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import legalmanagement.databaseconn_1;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author jimmelbermudez7
 */
public class monitoring extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null; 
    /**
     * Creates new form monitoring
     */
    public monitoring() {
        initComponents();
                conn = databaseconn_1.ConnecrDb();
                
    }
private void facility(){

        try{
           
           String sql = "select AMFacilityID as FacilityID,AMAddress as Facility,AMCapacity as Capacity,AMStatus as Status from Log1AssetMgt_Facility";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tblfacility.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
        
    }  
//private void reserved(){
//
//        try{
//           
//           String sql = "select from Core1CMRegistration";
//           pst=conn.prepareStatement(sql);
//           
//           rs = pst.executeQuery();
//           tblreserved.setModel(DbUtils.resultSetToTableModel(rs));
//          }
//            catch(Exception e){
//           JOptionPane.showMessageDialog(null, e);
//           }
//        
//    }    



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblreserved = new javax.swing.JTable();
        Event = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fname1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblfacility = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fcapacity = new javax.swing.JTextField();
        fstatus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));
        setPreferredSize(new java.awt.Dimension(1220, 580));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 192, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(108, 192, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true), "RESERVED FACILITY", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblreserved.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblreserved);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 590, 430));
        jPanel3.add(Event, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 180, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Event:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Facility Name:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, 20));
        jPanel3.add(fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Date:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, 20));
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 180, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 580));

        jPanel4.setBackground(new java.awt.Color(108, 192, 240));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true), "FACILITY", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblfacility.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblfacility.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblfacilityAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblfacility.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblfacilityMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblfacility);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 590, 230));

        image.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jDesktopPane1.add(image);
        image.setBounds(0, 0, 570, 190);

        jPanel4.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 190));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Facility Name:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        fname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 380, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Facility Capacity:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 140, 30));

        fcapacity.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fcapacity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(fcapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 380, 30));

        fstatus.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fstatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(fstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 380, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Status:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 580));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void tblfacilityAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblfacilityAncestorAdded
facility();        // TODO add your handling code here:
    }//GEN-LAST:event_tblfacilityAncestorAdded

    private void tblfacilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblfacilityMouseClicked
        int row =tblfacility.getSelectedRow();
            String Table_click=(tblfacility.getModel().getValueAt(row,0).toString());
        try{
        String sql="SELECT * from Log1AssetMgt_Facility where AMFacilityID='"+Table_click+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if (rs.next()) {
            byte[]imagedata =rs.getBytes("AMPicture");
            format =new ImageIcon(imagedata);
            image.setIcon(format);
        }
        
    }catch(Exception e){
        e.printStackTrace();
    }
        
        try{
            
            String sql="SELECT * from Log1AssetMgt_Facility where AMFacilityID='"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 =rs.getString("AMAddress");
                fname.setText(add1);
                String add2 =rs.getString("AMCapacity");
                fcapacity.setText(add2);
                String add3 =rs.getString("AMStatus");
                fstatus.setText(add3);                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblfacilityMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Event;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField fcapacity;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fname1;
    private javax.swing.JTextField fstatus;
    private javax.swing.JLabel image;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblfacility;
    private javax.swing.JTable tblreserved;
    // End of variables declaration//GEN-END:variables
private ImageIcon format =null;
}
