/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package documentmanagement;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author jimmelbermudez7
 */
public class dmsubmodules extends javax.swing.JPanel {
GridBagLayout layout=new GridBagLayout();
     documentrequest a1;
     documents a2;
     deployment a3;
     documentreports a4;
     DM a5;
    /**
     * Creates new form docusubmodules
     */
    public dmsubmodules() {
        initComponents();
        a1=new documentrequest();
        a2=new documents();
        a3=new deployment();
        a4=new documentreports();
        a5=new DM();
        home.setLayout(layout);
        GridBagConstraints a=new GridBagConstraints();
        a.gridx=0;
        a.gridy=0;
        home.add(a1,a);
        home.add(a2,a);
        home.add(a3,a);
        home.add(a4,a);
        home.add(a5,a);
         a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(false);
         a5.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        document = new javax.swing.JButton();
        deployment = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        home = new javax.swing.JPanel();
        reports1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));
        setPreferredSize(new java.awt.Dimension(1220, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 192, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        document.setBackground(new java.awt.Color(0, 204, 255));
        document.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        document.setText("Archieved Documents");
        document.setToolTipText("");
        document.setBorder(null);
        document.setContentAreaFilled(false);
        document.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        document.setOpaque(true);
        document.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                documentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                documentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                documentMouseExited(evt);
            }
        });
        document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentActionPerformed(evt);
            }
        });
        jPanel1.add(document, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 200, 30));

        deployment.setBackground(new java.awt.Color(0, 204, 255));
        deployment.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        deployment.setText("Deployment");
        deployment.setToolTipText("");
        deployment.setBorder(null);
        deployment.setContentAreaFilled(false);
        deployment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deployment.setOpaque(true);
        deployment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deploymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deploymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deploymentMouseExited(evt);
            }
        });
        deployment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deploymentActionPerformed(evt);
            }
        });
        jPanel1.add(deployment, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, 30));

        reports.setBackground(new java.awt.Color(0, 204, 255));
        reports.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reports.setText("D");
        reports.setToolTipText("");
        reports.setBorder(null);
        reports.setContentAreaFilled(false);
        reports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reports.setOpaque(true);
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        jPanel1.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        home.setBackground(new java.awt.Color(108, 192, 240));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1220, 580));

        reports1.setBackground(new java.awt.Color(0, 204, 255));
        reports1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reports1.setText("Reports");
        reports1.setToolTipText("");
        reports1.setBorder(null);
        reports1.setContentAreaFilled(false);
        reports1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reports1.setOpaque(true);
        reports1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reports1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reports1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reports1MouseExited(evt);
            }
        });
        reports1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reports1ActionPerformed(evt);
            }
        });
        jPanel1.add(reports1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 200, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void documentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_documentMouseClicked

    private void documentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentMouseEntered


        // TODO add your handling code here:
    }//GEN-LAST:event_documentMouseEntered

    private void documentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentMouseExited


        // TODO add your handling code here:
    }//GEN-LAST:event_documentMouseExited

    private void documentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentActionPerformed
reports.setForeground(new java.awt.Color(000,000,000));
document.setForeground(new java.awt.Color(255,255,255));
deployment.setForeground(new java.awt.Color(000,000,000));
reports1.setForeground(new java.awt.Color(000,000,000));
        a1.setVisible(false);
         a2.setVisible(true);
         a3.setVisible(false);
         a4.setVisible(false);
         a5.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_documentActionPerformed

    private void deploymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deploymentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deploymentMouseClicked

    private void deploymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deploymentMouseEntered
  // TODO add your handling code here:
    }//GEN-LAST:event_deploymentMouseEntered

    private void deploymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deploymentMouseExited
    // TODO add your handling code here:
    }//GEN-LAST:event_deploymentMouseExited

    private void deploymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deploymentActionPerformed
reports.setForeground(new java.awt.Color(000,000,000));
document.setForeground(new java.awt.Color(000,000,000));
deployment.setForeground(new java.awt.Color(255,255,255));
reports1.setForeground(new java.awt.Color(000,000,000));
        a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(true);
         a4.setVisible(false);    
         a5.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_deploymentActionPerformed

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseClicked

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
     // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
     // TODO add your handling code here:
    }//GEN-LAST:event_reportsMouseExited

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
reports.setForeground(new java.awt.Color(255,255,255));
document.setForeground(new java.awt.Color(000,000,000));
deployment.setForeground(new java.awt.Color(000,000,000));
reports1.setForeground(new java.awt.Color(000,000,000));
        a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(false);
         a5.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_reportsActionPerformed

    private void reports1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseClicked

    private void reports1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseEntered

    private void reports1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reports1MouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_reports1MouseExited

    private void reports1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reports1ActionPerformed
reports.setForeground(new java.awt.Color(000,000,000));
document.setForeground(new java.awt.Color(000,000,000));
deployment.setForeground(new java.awt.Color(000,000,000));
reports1.setForeground(new java.awt.Color(255,255,255));
        a1.setVisible(false);
         a2.setVisible(false);
         a3.setVisible(false);
         a4.setVisible(true); 
a5.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_reports1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deployment;
    private javax.swing.JButton document;
    private javax.swing.JPanel home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reports;
    private javax.swing.JButton reports1;
    // End of variables declaration//GEN-END:variables
}
