package administrative3206;



import documentmanagement.databaseconn;
import administrative3206.template;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class NewJFramelogin extends javax.swing.JFrame {
     Connection conn = null;   
     PreparedStatement pst = null;  
     ResultSet rs = null;

    /**
     * Creates new form NewJFramelogin
     */
    public NewJFramelogin() {
        initComponents();
        Core1();
        conn = databaseconn.ConnecrDb();
    }
    public void Core1(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);
    
     String tpattern = "hh:mm";
                    SimpleDateFormat tsdf = new SimpleDateFormat(tpattern);
                    time.setText(tsdf.format(new java.util.Date()));
                    
    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
            ps.setText(day_night);
  //  time1.setText(hour+":"+mins+":"+secs); 



int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }
} } };

clock.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        radio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ps = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 192, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 192, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Username:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 84, 26));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 84, 26));

        User.setBackground(new java.awt.Color(108, 192, 240));
        User.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        User.setBorder(null);
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        jPanel2.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 270, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 280, 10));

        Pass.setBackground(new java.awt.Color(108, 192, 240));
        Pass.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Pass.setBorder(null);
        Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassMouseClicked(evt);
            }
        });
        Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PassKeyReleased(evt);
            }
        });
        jPanel2.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 30));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log In");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 160, 90, 30));

        radio.setBackground(new java.awt.Color(51, 204, 255));
        radio.setText("See Password");
        radio.setContentAreaFilled(false);
        radio.setOpaque(true);
        radio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioItemStateChanged(evt);
            }
        });
        jPanel2.add(radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 203));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("USER ACCOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("    x");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 30, 20));

        ps.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ps.setText("pm");
        jPanel1.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 42, 20));

        date.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        date.setText("ooooooooooooooooo");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 160, 20));

        time.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        time.setText("ooooo");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrative3206/banner log.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
       User.setText("");
    }//GEN-LAST:event_UserMouseClicked

    private void PassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassMouseClicked
        Pass.setText("");
    }//GEN-LAST:event_PassMouseClicked

    private void PassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
             String sql = " select * from GrabLogin where username=? and password=?";
        
   try {            
        pst=conn.prepareStatement(sql);           
        pst.setString(1,User.getText());           
        pst.setString(2,Pass.getText());          
        rs=pst.executeQuery();
        
        
        String Uname = User.getText();
            String Pword = Pass.getText();
            
            
            if(Uname.isEmpty()&& !Pword.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter your Username","Warning",JOptionPane.WARNING_MESSAGE);
                
            }
            else if(!Uname.isEmpty()&& Pword.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter your Password","Warning",JOptionPane.WARNING_MESSAGE);
                
            }
            else if(Uname.isEmpty() && Pword.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter your Username and Password","Warning",JOptionPane.WARNING_MESSAGE);
                
            }
            
        if(rs.next()){               
        JOptionPane.showMessageDialog(null, "Username and Password are correct");
        pst.execute();
        
        rs.close();               
        pst.close();               
        dispose();
        
        template s = new template();
        s.setVisible(true);
        
        }
        else{               
        JOptionPane.showMessageDialog(null, "Username and Password are not correct","ERROR",JOptionPane.ERROR_MESSAGE);   

        User.setText("");
        
        Pass.setText("");
        User.grabFocus();    
        }
   }        
   catch(Exception e){
   JOptionPane.showMessageDialog(null, e);     

   }
            
            
            
            
        }
    }//GEN-LAST:event_PassKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    String sql = " select * from GrabLogin where username=? and password=?";
        
   try {            
        pst=conn.prepareStatement(sql);           
        pst.setString(1,User.getText());           
        pst.setString(2,Pass.getText());          
        rs=pst.executeQuery();
        
        
        String Uname = User.getText();
            String Pword = Pass.getText();
            
            
            if(Uname.isEmpty()&& !Pword.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter your Username","Warning",JOptionPane.WARNING_MESSAGE);
                
            }
            else if(!Uname.isEmpty()&& Pword.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter your Password","Warning",JOptionPane.WARNING_MESSAGE);
                
            }
            else if(Uname.isEmpty() && Pword.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter your Username and Password","Warning",JOptionPane.WARNING_MESSAGE);
                
            }
            
        if(rs.next()){               
        JOptionPane.showMessageDialog(null, "Username and Password are correct");
        pst.execute();
        
        rs.close();               
        pst.close();               
        dispose();
        
        template s = new template();
        s.setVisible(true);
        
        }
        else{               
        JOptionPane.showMessageDialog(null, "Username and Password are not correct","ERROR",JOptionPane.ERROR_MESSAGE);   

        User.setText("");
        
        Pass.setText("");
        User.grabFocus();    
        }
   }        
   catch(Exception e){
   JOptionPane.showMessageDialog(null, e);     

   }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void radioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioItemStateChanged
if (radio.isSelected()){
    Pass.setEchoChar((char)0);  
}
else{
    Pass.setEchoChar('*');
}
// TODO add your handling code here:
    }//GEN-LAST:event_radioItemStateChanged

    private void PassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassKeyReleased
if(Pass.getText().isEmpty()){
 radio.setVisible(false);
 radio.setSelected(false);

}
else{
    radio.setVisible(true);
}// TODO add your handling code here:
    }//GEN-LAST:event_PassKeyReleased

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
jButton1.setForeground(new java.awt.Color(102,204,255));
jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102,204,255), 2));
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
jButton1.setForeground(new java.awt.Color(255,255,255));
jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255), 2));

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
jLabel5.setForeground(new java.awt.Color(102,204,255));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
 jLabel5.setForeground(new java.awt.Color(0,0,0)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFramelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFramelogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pass;
    private javax.swing.JTextField User;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel ps;
    private javax.swing.JRadioButton radio;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
