/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legalmanagement;

import documentmanagement.databaseconn;
import java.awt.Color;
import java.io.File;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jimmel Bermudez
 */
public class attachment extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null; 
    /**
     * Creates new form attachment
     */
    public attachment() {
        initComponents();       
         conn = databaseconn.ConnecrDb();
        File();
        date();
        File1();
        date.setVisible(false);
        approved.setVisible(false);
        disapproved.setVisible(false);
     docu();
   
    }
    private void File1(){

        try{
           
           String sql;
            sql = "select LMAttachno as No,LMRequestno as Reqno,LMDocumentName as Document,LMQuantity as Qty,LMStatus as Status from AdminLMAttachDocu";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl2.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
    }
    private void File(){

        try{
           
           String sql = "select LMRequestno as RID,LMId as ID,concat(LMLname,', ',LMFname,' ',LMMi) as Name,LMTypeofdocu as Type,LMQuantity as Qnty from AdminLMDocuRequest where LMStatus='Pending'";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
        
    }
    public void date(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);
                    
    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
  //  time1.setText(hour+":"+mins+":"+secs); 


date.setVisible(false);
int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }
} } };

clock.start();
}
private void docu(){
    
        try {
            String value1 = name.getText();            
            String sql= "select LMPath from AdminLMDocument where LMDocumentName='"+value1+"'";            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
            String add1=rs.getString("LMPath");
            path.setText(add1);
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        app = new javax.swing.JButton();
        approved = new javax.swing.JLabel();
        dis = new javax.swing.JButton();
        disapproved = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        ewqewqeqwe = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        quan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        purpose = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        attach = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 192, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText(",");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 10, 30));

        jPanel3.setBackground(new java.awt.Color(108, 192, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true), "REQUESTI INFORMATION", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        app.setBackground(new java.awt.Color(0, 102, 204));
        app.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        app.setForeground(new java.awt.Color(255, 255, 255));
        app.setText("Approved");
        app.setContentAreaFilled(false);
        app.setOpaque(true);
        app.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appActionPerformed(evt);
            }
        });
        jPanel3.add(app, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 140, 30));

        approved.setText("Approved");
        jPanel3.add(approved, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 60, 30));

        dis.setBackground(new java.awt.Color(0, 102, 204));
        dis.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dis.setForeground(new java.awt.Color(255, 255, 255));
        dis.setText("Disapproved");
        dis.setContentAreaFilled(false);
        dis.setOpaque(true);
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        jPanel3.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 140, 30));

        disapproved.setText("Disapproved");
        jPanel3.add(disapproved, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, 30));

        rid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ridKeyReleased(evt);
            }
        });
        jPanel3.add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 440, 30));

        ewqewqeqwe.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ewqewqeqwe.setText("Request number:");
        jPanel3.add(ewqewqeqwe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 20));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 440, 30));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel24.setText("I.D Number:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 20));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Name:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 20));

        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnameKeyReleased(evt);
            }
        });
        jPanel3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 30));

        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameKeyReleased(evt);
            }
        });
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 180, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel10.setText("M.I");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 110, -1));

        mi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                miKeyReleased(evt);
            }
        });
        jPanel3.add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 60, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel9.setText("Firstname");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel7.setText("Lastname");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setText("Department:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 20));

        department.setEditable(false);
        jPanel3.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 440, 30));

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 440, 30));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel25.setText(" Name of Document:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 20));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel28.setText("Quantity:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        quan.setEditable(false);
        jPanel3.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 440, 30));

        purpose.setEditable(false);
        purpose.setColumns(20);
        purpose.setRows(5);
        jScrollPane3.setViewportView(purpose);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 440, 50));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel27.setText("Purpose:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 20));

        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });
        jPanel3.add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 360, 30));

        date.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        date.setText("Id no.:");
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, 30));

        attach.setBackground(new java.awt.Color(0, 102, 204));
        attach.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        attach.setForeground(new java.awt.Color(255, 255, 255));
        attach.setText("Attach");
        attach.setContentAreaFilled(false);
        attach.setOpaque(true);
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });
        jPanel3.add(attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 80, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 460, 550));

        jPanel4.setBackground(new java.awt.Color(108, 192, 240));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true), "NEW REQUEST FOR DOCUMENT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 240));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 275));

        jPanel5.setBackground(new java.awt.Color(108, 192, 240));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true), "APPROVED DOCUMENT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl2);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 240));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 760, 275));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
//JTableHeader j= tbl.getTableHeader();
//j.setBackground(Color.blue);
        File();        // TODO add your handling code here:
    }//GEN-LAST:event_tblAncestorAdded

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
    int row =tbl.getSelectedRow();
            String Table_click=(tbl.getModel().getValueAt(row,0).toString());
        try{
        String sql="SELECT * from AdminLMDocuRequest where LMRequestno='"+Table_click+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if (rs.next()) {
            
            String add1 = rs.getString("LMId");
            id.setText(add1);
            String add2 = rs.getString("LMLname");
            lname.setText(add2);
            String add3 = rs.getString("LMFname");
            fname.setText(add3);
            String add4 = rs.getString("LMMi");
            mi.setText(add4);
            String add5 = rs.getString("LMDepartment");
            department.setText(add5);
            String add6 = rs.getString("LMTypeofdocu");
            name.setText(add6);
            String add7 = rs.getString("LMQuantity");
            quan.setText(add7);
            String add8 = rs.getString("LMRequestno");
            rid.setText(add8);
            String add9 = rs.getString("LMPurpose");
            purpose.setText(add9);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
        String value=(tbl.getModel().getValueAt(row, 4).toString());
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+value);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void ridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ridKeyReleased
String a=rid.getText();
         try {
            
            String sql= "SELECT LMRequestno as RID,LMId as ID,concat(LMLname,', ',LMFname,' ',LMMi) as Name,LMTypeofdocu as Type,LMQuantity as Qnty from AdminLMDocuRequest where LMRequestno='"+a+"'";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_ridKeyReleased

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
String a=id.getText();
         try {
            
            String sql= "SELECT LMRequestno as RID,LMId as ID,concat(LMLname,', ',LMFname,' ',LMMi) as Name,LMTypeofdocu as Type,LMQuantity as Qnty from AdminLMDocuRequest where LMId='"+a+"'";
             
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyReleased

    private void lnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyReleased
String a=lname.getText();
         try {
            
            String sql= "SELECT LMRequestno as RID,LMId as ID,concat(LMLname,', ',LMFname,' ',LMMi) as Name,LMTypeofdocu as Type,LMQuantity as Qnty from AdminLMDocuRequest where LMLname='"+a+"'";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lnameKeyReleased

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
 try{
            
        String sql2 = "insert into AdminLMAttachDocu (LMRequestno,LMDocumentName,LMDocument,LMQuantity,LMStatus,LMDate)values(?,?,?,?,?,?)";
            

    pst=conn.prepareStatement(sql2);
    pst.setString(1, rid.getText());
    pst.setString(2, name.getText());
    pst.setString(3, path.getText());            
    pst.setString(4, quan.getText());
    pst.setString(5, disapproved.getText());
    pst.setString(6, date.getText());
            
    pst.execute();            
    rid.setText("");           
    lname.setText("");
    fname.setText("");
    mi.setText(""); 
    path.setText("");           
    quan.setText(""); 
    
    
      JOptionPane.showMessageDialog(null, "Saved");
      
      
             
        } catch (Exception e) {   
            JOptionPane.showMessageDialog(null, e);
         }

    try{
       String value1 = id.getText();
       String value2 = disapproved.getText();
     
       String sql="update AdminLMDocuRequest set LMStatus='"+value2+"' where LMRequestno='"+value1+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       id.setText("");           
       
       JOptionPane.showMessageDialog(null, "Updated");
       }
        catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
        }
File();
File1();      // TODO add your handling code here:
    }//GEN-LAST:event_disActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
     
        try {
            String value1 = name.getText();            
            String sql= "select LMPath from AdminLMDocument where LMDocumentName='"+value1+"'";            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
            String add1=rs.getString("LMPath");
            path.setText(add1);
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
docu();

    }//GEN-LAST:event_nameKeyReleased

    private void appActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appActionPerformed
  try{
            
        String sql2 = "insert into AdminLMAttachDocu (LMRequestno,LMDocumentName,LMDepartment,LMDocument,LMQuantity,LMStatus,LMDate)values(?,?,?,?,?,?,?)";
            

    pst=conn.prepareStatement(sql2);
    pst.setString(1, rid.getText());
    pst.setString(2, name.getText());
    pst.setString(3, department.getText());
    pst.setString(4, path.getText());            
    pst.setString(5, quan.getText());
    pst.setString(6, approved.getText());
    pst.setString(7, date.getText());
            
    pst.execute();            
    rid.setText("");           
    lname.setText("");
    fname.setText("");
    mi.setText(""); 
    path.setText("");           
    quan.setText(""); 
    department.setText(""); 

    
      JOptionPane.showMessageDialog(null, "Saved");
      
      
             
        } catch (Exception e) {   
            JOptionPane.showMessageDialog(null, e);
         }
File();
    try{
       String value1 = id.getText();
       String value2 = approved.getText();
     
       String sql="update AdminLMDocuRequest set LMStatus='"+value2+"' where LMRequestno='"+value1+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       id.setText("");           
       
       
       }
        catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
        }
File();
// TODO add your handling code here:
    }//GEN-LAST:event_appActionPerformed

    private void tbl2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl2AncestorAdded
        File1();        // TODO add your handling code here:
    }//GEN-LAST:event_tbl2AncestorAdded

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        docu();        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attachActionPerformed

    private void miKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_miKeyReleased
        String a=mi.getText();
        try {

            String sql= "SELECT LMRequestno as RID,LMId as ID,concat(LMLname,', ',LMFname,' ',LMMi) as Name,LMTypeofdocu as Type,LMQuantity as Qnty from AdminLMDocuRequest where LMMi='"+a+"'";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_miKeyReleased

    private void fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyReleased
        String a=fname.getText();
        try {

            String sql= "SELECT LMRequestno as RID,LMId as ID,concat(LMLname,', ',LMFname,' ',LMMi) as Name,LMTypeofdocu as Type,LMQuantity as Qnty from AdminLMDocuRequest where LMFname='"+a+"'";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fnameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton app;
    private javax.swing.JLabel approved;
    private javax.swing.JButton attach;
    private javax.swing.JLabel date;
    private javax.swing.JTextField department;
    private javax.swing.JButton dis;
    private javax.swing.JLabel disapproved;
    private javax.swing.JLabel ewqewqeqwe;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mi;
    private javax.swing.JTextField name;
    private javax.swing.JTextField path;
    private javax.swing.JTextArea purpose;
    private javax.swing.JTextField quan;
    private javax.swing.JTextField rid;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tbl2;
    // End of variables declaration//GEN-END:variables
private ImageIcon format =null;
String filename=null;
int s=0;
byte[] person_image=null;
}

