/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legalmanagement;

import documentmanagement.databaseconn;
import java.awt.Desktop;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jimmel Bermudez
 */
public class documentss extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
    /**
     * Creates new form documentss
     */
    public documentss() {
        initComponents();
        conn = databaseconn.ConnecrDb();
        active.setVisible(false);
        date.setVisible(false);
        archieved.setVisible(false);
        date();
        activedocument();
    tblarchieve();
    activedocuarchived();
    }
    public void date(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);
                    
    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
  //  time1.setText(hour+":"+mins+":"+secs); 

 
date.setVisible(false);
int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }
} } };

clock.start();
}
public void update(){
     try{
       String value1 = did.getText();

       String sql="update AdminLMDocument set LMStatus='Archieved' where LMDocumentId='"+value1+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       JOptionPane.showMessageDialog(null, "Updated");
       }catch(Exception e){
       JOptionPane.showMessageDialog(null, e);

}
}
public void activedocument(){
        try{
           
           String sql = "select LMDocumentId as ID,LMDocumentType as Document,LMDocumentName as Name,LMPath as Path from AdminLMDocument where LMStatus='Active'";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           tbl3.setModel(DbUtils.resultSetToTableModel(rs));
        }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }

    }
        public void activedocuarchived(){
        try{
           
           String sql = "select LMDocumentId as Id,LMDocumentName as Name from AdminLMDocument where LMStatus='Active'";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           activetable.setModel(DbUtils.resultSetToTableModel(rs));
        }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }

    }

public void tblarchieve(){
        try{
           
           String sql = "select DMArchievedno as ID,DMDocumentId as Document,DMDocumentName as Name,DMDocumentType as Type,DMDate as Date from AdminDMArchieved";
           pst=conn.prepareStatement(sql);
           
           rs = pst.executeQuery();
           archievetable.setModel(DbUtils.resultSetToTableModel(rs));
          }
            catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        archieve = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        archievetable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        activetable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        dname = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        dtype = new javax.swing.JTextField();
        did = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        archieved = new javax.swing.JLabel();
        dpath = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        adddoc = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl3 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        legal = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        active = new javax.swing.JLabel();
        docuname = new javax.swing.JTextField();
        path = new javax.swing.JTextField();
        attach = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        adddocu = new javax.swing.JButton();
        open = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tree1 = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree3 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree2 = new javax.swing.JTree();

        jPanel2.setBackground(new java.awt.Color(108, 192, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(925, 500));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        archievetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        archievetable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                archievetableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(archievetable);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 890, 200));

        jPanel3.setBackground(new java.awt.Color(108, 192, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2), "Active Documents", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        activetable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                activetableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        activetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activetableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(activetable);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 220));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 250));

        jPanel5.setBackground(new java.awt.Color(108, 192, 240));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2), "Archiving Document", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel5.add(dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 400, 30));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel22.setText("Document I.D:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 300, 30));

        dtype.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel5.add(dtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 400, 30));

        did.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddidActionPerformed(evt);
            }
        });
        jPanel5.add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 400, 30));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel23.setText("Document Name:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel24.setText("Document Type:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 30));

        archieved.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        archieved.setText("Archieved");
        jPanel5.add(archieved, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, 30));

        dpath.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel5.add(dpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 400, 30));

        jButton6.setBackground(new java.awt.Color(0, 102, 204));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Archieve");
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 100, 30));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel27.setText("Document Path:");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 550, 250));

        archieve.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(108, 192, 240));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        jPanel4.setPreferredSize(new java.awt.Dimension(925, 500));
        jPanel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane5.setViewportView(tbl3);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 890, 260));

        jPanel6.setBackground(new java.awt.Color(108, 192, 240));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2), "To Add Document", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        legal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        legal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Legal Contract", "Legal Permit", "Terms & Policy", " " }));
        jPanel6.add(legal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 400, 30));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel30.setText("Document Type:");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 30));

        active.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        active.setText("Active");
        jPanel6.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 160, 30));

        docuname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel6.add(docuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 400, 30));

        path.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel6.add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 400, 30));

        attach.setBackground(new java.awt.Color(0, 102, 204));
        attach.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        attach.setForeground(new java.awt.Color(255, 255, 255));
        attach.setText("Attach");
        attach.setContentAreaFilled(false);
        attach.setOpaque(true);
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });
        jPanel6.add(attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 30));

        jButton9.setBackground(new java.awt.Color(0, 102, 204));
        jButton9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Save");
        jButton9.setContentAreaFilled(false);
        jButton9.setOpaque(true);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 110, 30));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel29.setText("Document Name:");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        date.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel6.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 160, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 890, 180));

        adddoc.getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(108, 192, 240));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 192, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("CONTRACT");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 80, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("PERMITS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 70, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("TERMS & POLICY");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 120, 30));

        adddocu.setBackground(new java.awt.Color(0, 102, 204));
        adddocu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        adddocu.setText("Add Document");
        adddocu.setToolTipText("");
        adddocu.setBorder(null);
        adddocu.setBorderPainted(false);
        adddocu.setContentAreaFilled(false);
        adddocu.setOpaque(true);
        adddocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddocuActionPerformed(evt);
            }
        });
        jPanel1.add(adddocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 140, 40));

        open.setBackground(new java.awt.Color(0, 102, 204));
        open.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        open.setText("OPEN FILE");
        open.setContentAreaFilled(false);
        open.setOpaque(true);
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jPanel1.add(open, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 120, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("Add Archieve Document");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        tree1.setModel(new FileSystemModel(new File("C:\\Users\\Jimmel Bermudez\\Desktop\\contracts")));
        tree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tree1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 320, 360));

        jtree3.setModel(new FileSystemModel(new File("C:\\Users\\Jimmel Bermudez\\Desktop\\permits")));
        jtree3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtree3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 300, 360));

        tree2.setModel(new FileSystemModel(new File("C:\\Users\\Jimmel Bermudez\\Desktop\\terms and policy")));
        tree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tree2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tree2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 330, 360));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void adddocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddocuActionPerformed
adddoc.setVisible(true);
        // TODO add your handling code here:
//        try {
//            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Microsoft Office\\Microsoft Office Word 2007");
//        }
//        catch (Exception e)
//        {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_adddocuActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
     try{
         File Selection=new File(Jtreevar);
         if(Selection.exists()){
         if(Desktop.isDesktopSupported()){
             Desktop.getDesktop().open(Selection);             
         }else{
             JOptionPane.showMessageDialog(null, "cant open file");
         }             
         }else{
         JOptionPane.showMessageDialog(null, "cant open file");
         
         }
         
     }catch(Exception ex) {
         JOptionPane.showMessageDialog(null, "cant open file");
     }
        
    }//GEN-LAST:event_openActionPerformed

    private void tree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree1MouseClicked
        Jtreevar=tree1.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");
    }//GEN-LAST:event_tree1MouseClicked

    private void jtree3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree3MouseClicked
        Jtreevar=jtree3.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");        // TODO add your handling code here:
    }//GEN-LAST:event_jtree3MouseClicked

    private void tree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tree2MouseClicked
        Jtreevar=tree2.getSelectionPath().toString().replaceAll("[\\[\\]]", "").replace(", ", "\\");
    }//GEN-LAST:event_tree2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        String a = this.Id.getText();
//        String b = this.lname.getText();
//        String c1 = this.fname.getText();
//        String d = this.mi.getText();
//        String e = this.Id2.getText();
//        String f = this.lname2.getText();
//        String g = this.fname2.getText();
//        String h = this.mi2.getText();
//        String i = this.complain.getText();
//
//        if (a.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Id of Complainant is Empty");
//        }
//        else if (b.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Lastname of Complainant is Empty");
//        }
//        if (c1.isEmpty()){
//              JOptionPane.showMessageDialog(null, "Firstname of Complainant is Number");
//        }
//        else if (d.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Middle Initial of Complainant is Empty");
//        }
//        if (e.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Id of Respondent is Empty");
//        }
//        else if (f.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Lastname of Respondent is empty");
//        }
//        if (g.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Firstname of Respondent is empty");
//        }
//        else if (h.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Middle Initial of Respondent is empty");
//        }
//        if (i.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Complain is Empty");
//        }
//
//        else {
//            try{
//
//                String sql = "insert into AdminLMComplaints (LMComplainantId,LMCType,LMCLname,LMCFname,LMCMi,LMRType,LMRespondentId,LMRLname,LMRFname,LMRMi,LMComplain,LMDate)values(?,?,?,?,?,?,?,?,?,?,?,?)";
//
//                pst=conn.prepareStatement(sql);
//                pst.setString(1, Id.getText());
//                pst.setString(2, Customer.getText());
//                pst.setString(3, lname.getText());
//                pst.setString(4, fname.getText());
//                pst.setString(5, mi.getText());
//                String value = type.getSelectedItem().toString();
//                pst.setString(6, value);
//                pst.setString(7, Id2.getText());
//                pst.setString(8, lname2.getText());
//                pst.setString(9, fname2.getText());
//                pst.setString(10, mi2.getText());
//                pst.setString(11, complain.getText());
//                pst.setString(12, date.getText());
//
//                pst.execute();
//            } catch (SQLException ex) {
//                Logger.getLogger(complaintscostumer.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            try{
//
//                String sql1 = "insert into AdminLMComplainant (LMId,LMType,LMCLname,LMCFname,LMCMi)values(?,?,?,?,?)";
//
//                pst=conn.prepareStatement(sql1);
//                pst.setString(1, Id.getText());
//                pst.setString(2, Customer.getText());
//                pst.setString(3, lname.getText());
//                pst.setString(4, fname.getText());
//                pst.setString(5, mi.getText());
//
//                pst.execute();
//
//            } catch (SQLException ex) {
//                Logger.getLogger(complaintscostumer.class.getName()).log(Level.SEVERE, null, ex);
//            }
            try{

                String sql2 = "insert into AdminDMArchieved(DMDocumentId,DMDocumentName,DMDocumentType,DMDocument,DMStatus,DMDate)values(?,?,?,?,?,?)";

                pst=conn.prepareStatement(sql2);
                pst.setString(1, did.getText());
                pst.setString(2, dname.getText());
                pst.setString(3, dtype.getText());
                pst.setString(4, dpath.getText());
                pst.setString(5, archieved.getText());
                pst.setString(6, date.getText());

                pst.execute();
                did.setText("");
                dname.setText("");
                dtype.setText("");
                dpath.setText("");

                JOptionPane.showMessageDialog(null, "Saved");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

    
update();
activedocuarchived();
tblarchieve();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        archieve.setBounds(200,150,925, 500);      // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
archieve.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ddidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddidActionPerformed

    private void jPanel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel4AncestorAdded
        adddoc.setBounds(200,150,925, 500);          // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4AncestorAdded

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        path.setText(filename);

        // TODO add your handling code here:
    }//GEN-LAST:event_attachActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
     try{

                String sql2 = "insert into AdminLMDocument (LMDocumentType,LMDocumentName,LMPath,LMStatus,LMDate)values(?,?,?,?,?)";

                pst=conn.prepareStatement(sql2);
                String value = legal.getSelectedItem().toString();
                pst.setString(1, value);
                pst.setString(2, docuname.getText());
                
                pst.setString(3, path.getText());
                pst.setString(4, active.getText());
                pst.setString(5, date.getText());

                pst.execute();
                docuname.setText("");
                path.setText("");
                JOptionPane.showMessageDialog(null, "Saved");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
activedocument();                // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tbl3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl3AncestorAdded
activedocument();        // TODO add your handling code here:
    }//GEN-LAST:event_tbl3AncestorAdded

    private void activetableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_activetableAncestorAdded
activedocuarchived();        // TODO add your handling code here:
    }//GEN-LAST:event_activetableAncestorAdded

    private void archievetableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_archievetableAncestorAdded
tblarchieve();        // TODO add your handling code here:
    }//GEN-LAST:event_archievetableAncestorAdded

    private void activetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activetableMouseClicked
    int row =activetable.getSelectedRow();
            String Table_click=(activetable.getModel().getValueAt(row,0).toString());
        try{
        String sql="select * from AdminLMDocument where LMDocumentId='"+Table_click+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if (rs.next()) {
            
            String add1 = rs.getString("LMDocumentId");
            did.setText(add1);
            String add2 = rs.getString("LMDocumentName");
            dname.setText(add2);
            String add3 = rs.getString("LMDocumentType");
            dtype.setText(add3);
            String add4 = rs.getString("LMPath");
            dpath.setText(add4);
            }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }                // TODO add your handling code here:
    }//GEN-LAST:event_activetableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel active;
    private javax.swing.JTable activetable;
    private javax.swing.JDialog adddoc;
    private javax.swing.JButton adddocu;
    private javax.swing.JDialog archieve;
    private javax.swing.JLabel archieved;
    private javax.swing.JTable archievetable;
    private javax.swing.JButton attach;
    private javax.swing.JLabel date;
    private javax.swing.JTextField did;
    private javax.swing.JTextField dname;
    private javax.swing.JTextField docuname;
    private javax.swing.JTextField dpath;
    private javax.swing.JTextField dtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTree jtree3;
    private javax.swing.JComboBox<String> legal;
    private javax.swing.JButton open;
    private javax.swing.JTextField path;
    private javax.swing.JTable tbl3;
    private javax.swing.JTree tree1;
    private javax.swing.JTree tree2;
    // End of variables declaration//GEN-END:variables
String Jtreevar;
String filename=null;
int s=0;
byte[] person_image=null;

}
