/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legalmanagement;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jimmel Bermudez
 */
public class requestdocuments extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null; 
    /**
     * Creates new form requestdocuments
     */
    public requestdocuments() {
        initComponents();
         conn = databaseconn_1.ConnecrDb();
        date();
        date.setVisible(false);
        Fillcombo();
    }
     private void Fillcombo(){

        try{
            String sql = "Select concat(LMDocumentType,', ',LMDocumentName) as name from AdminLMDocument where LMStatus='Active'";
           pst=conn.prepareStatement(sql);          
           rs = pst.executeQuery();
            
           while(rs.next()){
               String name=rs.getString("name");
               type.addItem(name);
               
           }
            
            
      
            
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);   
        }
     }
public void date(){
    Thread clock= new Thread(){
    public void run(){
    for(;;){
    Calendar calen = GregorianCalendar.getInstance();
    int AM_PM = calen.get(Calendar.AM_PM);
                    
    String [] days = new String [] {"","","","","","",""};
    String day_night = "";
            if (AM_PM==1)
            {day_night ="PM";}
            else
            {day_night = "AM";}
            
  //  time1.setText(hour+":"+mins+":"+secs); 


date.setVisible(false);
int mons = calen.get(Calendar.MONTH);
int day = calen.get(Calendar.DAY_OF_MONTH);
int yr = calen.get(Calendar.YEAR);
date.setText(days[calen.get(Calendar.DAY_OF_WEEK)-1]+" "+(mons+1)+"/"+day+"/"+yr);    
    try {
        sleep(1000);
    } catch (InterruptedException ex) {
        
    }
} } };

clock.start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        date = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        purpose = new javax.swing.JTextArea();
        save = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 192, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText(",");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 10, 30));

        jPanel2.setBackground(new java.awt.Color(108, 192, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true), "REQUEST DOCUMENT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel22.setText("I.D Number:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));

        id.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 30));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Name:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 20));

        lname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Lastname");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 20));

        fname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Firstname");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 140, 20));

        mi.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel2.add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 70, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("M.I");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 110, 20));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setText("Department:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 20));

        department.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel2.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 30));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setText("Name of Document:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 20));

        type.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 440, 30));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Quantity:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 20));

        quantity.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel2.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 280, 30));
        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 130, 130));

        date.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        date.setText("sdfghj");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 50, 30));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 590, 200));

        search.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 280, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Search Your Name:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 550));

        jPanel3.setBackground(new java.awt.Color(108, 192, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 3, true), "PURPOSE OF REQUESTING DOCUMENT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purpose.setColumns(20);
        purpose.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        purpose.setRows(5);
        jScrollPane2.setViewportView(purpose);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 240));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 270));

        save.setBackground(new java.awt.Color(0, 102, 204));
        save.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.setContentAreaFilled(false);
        save.setOpaque(true);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 120, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
try{
            
        String sql = "insert into AdminLMDocuRequest (LMId,LMLname,LMFname,LMMi,LMDepartment,LMTypeofdocu,LMQuantity,LMPurpose,LMDate)values(?,?,?,?,?,?,?,?,?)";
            

    pst=conn.prepareStatement(sql);
    pst.setString(1, id.getText());
    pst.setString(2, lname.getText());            
    pst.setString(3, fname.getText());
    pst.setString(4, mi.getText());           
    pst.setString(5, department.getText());
    String value = type.getSelectedItem().toString();
      pst.setString(6, value);
      pst.setString(7, quantity.getText());
      pst.setString(8, purpose.getText());          
    pst.setString(9, date.getText());
    
      
      
    pst.execute();
             
    id.setText("");           
    lname.setText("");
    fname.setText("");
    mi.setText(""); 
    department.setText("");           
    quantity.setText(""); 
    purpose.setText("");

    JOptionPane.showMessageDialog(null, "Request Saved");
        } catch (Exception e) {   
             JOptionPane.showMessageDialog(null, e);
         }        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void tblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAncestorAdded

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
//        int row =tbl.getSelectedRow();
//        String Table_click=(tbl.getModel().getValueAt(row,0).toString());
//        try{
//            String sql="SELECT * from AdminLMCustomer where CustomerId='"+Table_click+"'";
//            pst=conn.prepareStatement(sql);
//            rs=pst.executeQuery();
//            if (rs.next()) {
//
//                String add1 = rs.getString("CustomerId");
//                Id.setText(add1);
//                String add2 = rs.getString("Lname");
//                lname.setText(add2);
//                String add3 = rs.getString("Fname");
//                fname.setText(add3);
//                String add4 = rs.getString("Mi");
//                mi.setText(add4);
//                String add5 = rs.getString("Contactno");
//                contact.setText(add5);
//                String add6 = rs.getString("Email");
//                email.setText(add6);
//            }
//
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        String a=search.getText();
        try {

            String sql= "select CustomerId as ID,concat(Lname,', ',Fname,' ',Mi) as Name,Email from AdminLMCustomer where Lname='"+a+"'";

            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyReleased

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTextField department;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mi;
    private javax.swing.JTextArea purpose;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton save;
    private javax.swing.JTextField search;
    private javax.swing.JTable tbl;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
